name: acepool
description: "AcePool - Pool Game App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management (MVI pattern)
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Navigation
  go_router: ^15.1.0

  # Dependency injection
  get_it: ^8.0.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
